[package]
name = "mackerel-agent-rs"
version = "0.1.0"
authors = ["Krout0n <krouton@hatena.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2", features = ["yaml"]}
hostname = "^0.3"
mackerel_client = { git = "https://github.com/Krout0n/mackerel-client-rs" }
os-stat-rs = { git = "https://github.com/Krout0n/os-stat-rs" }
rust-ini = "0.15"
serde_json = "1.0.56"
tokio = { version = "0.2", features = ["full"] }
